# Generated by Django 2.0.5 on 2018-08-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180819_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='priority',
            field=models.CharField(choices=[('featured', 'Featured'), ('standard', 'Standard'), ('aside', 'Aside')], default='standard', max_length=10),
        ),
    ]
